import './globals.scss';
import { Inter } from 'next/font/google';
import Footer from './_components/Footer';
import Header from './_components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Home | E-Commerce Store',
    template: '%s | E-Commerce Store',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
